# RNN concepts
# End-to-end project on RNN

In [1]:
import numpy as np

In [2]:
docs = ['recurrent neural network',
		'neural network',
		'artificial neural',
		'connections between nodes',
		'can create a cycle',
		'allowing output',
		'some nodes to affect subsequent',
		'exhibit temporal',
		'dynamic behavior',
		'type of Neural Network',
    'affect subsequent']

In [3]:
pip install tensorflow


In [4]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

tokenizer = Tokenizer(oov_token='<nothing>')


In [5]:
tokenizer.fit_on_texts(docs)

In [6]:
tokenizer.word_index

{'<nothing>': 1,
 'neural': 2,
 'network': 3,
 'nodes': 4,
 'affect': 5,
 'subsequent': 6,
 'recurrent': 7,
 'artificial': 8,
 'connections': 9,
 'between': 10,
 'can': 11,
 'create': 12,
 'a': 13,
 'cycle': 14,
 'allowing': 15,
 'output': 16,
 'some': 17,
 'to': 18,
 'exhibit': 19,
 'temporal': 20,
 'dynamic': 21,
 'behavior': 22,
 'type': 23,
 'of': 24}

In [7]:
tokenizer.word_counts

OrderedDict([('recurrent', 1),
             ('neural', 4),
             ('network', 3),
             ('artificial', 1),
             ('connections', 1),
             ('between', 1),
             ('nodes', 2),
             ('can', 1),
             ('create', 1),
             ('a', 1),
             ('cycle', 1),
             ('allowing', 1),
             ('output', 1),
             ('some', 1),
             ('to', 1),
             ('affect', 2),
             ('subsequent', 2),
             ('exhibit', 1),
             ('temporal', 1),
             ('dynamic', 1),
             ('behavior', 1),
             ('type', 1),
             ('of', 1)])

In [8]:
tokenizer.document_count

11

In [9]:
sequences = tokenizer.texts_to_sequences(docs)
sequences

[[7, 2, 3],
 [2, 3],
 [8, 2],
 [9, 10, 4],
 [11, 12, 13, 14],
 [15, 16],
 [17, 4, 18, 5, 6],
 [19, 20],
 [21, 22],
 [23, 24, 2, 3],
 [5, 6]]

In [10]:
from keras.utils import pad_sequences

nsequences = pad_sequences(sequences,maxlen = 5, padding = 'post')
nsequences

array([[ 7,  2,  3,  0,  0],
       [ 2,  3,  0,  0,  0],
       [ 8,  2,  0,  0,  0],
       [ 9, 10,  4,  0,  0],
       [11, 12, 13, 14,  0],
       [15, 16,  0,  0,  0],
       [17,  4, 18,  5,  6],
       [19, 20,  0,  0,  0],
       [21, 22,  0,  0,  0],
       [23, 24,  2,  3,  0],
       [ 5,  6,  0,  0,  0]])

# movie-sentiment-Analysis using RNN 


In [11]:
from keras.datasets import imdb
imdb.load_data()

((array([list([1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 22665, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 21631, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 19193, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 10311, 8, 4, 107, 117, 5952, 15, 256, 4, 31050, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 12118, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32]),
         list([1, 19

In [12]:
from keras import Sequential
from keras.layers import Dense, SimpleRNN, Embedding, Flatten

In [13]:
(X_train, y_train), (X_test, y_test) = imdb.load_data()

In [14]:
print(len(X_train[0]))
print(len(X_train[2]))

218
141


## note:
   vector has different length we need to perform padding or pad sequences

In [15]:
print(y_train[7])
print(y_train[0])

0
1


In [16]:
from keras.utils import pad_sequences
maxlen = 500

X_train = pad_sequences(X_train , maxlen=maxlen, padding='post')  
X_test = pad_sequences(X_test , maxlen=maxlen, padding='post')  


In [17]:
print(len(X_train[0]))
print(len(X_train[2]))

500
500


In [18]:
X_train

array([[   1,   14,   22, ...,    0,    0,    0],
       [   1,  194, 1153, ...,    0,    0,    0],
       [   1,   14,   47, ...,    0,    0,    0],
       ...,
       [   1,   11,    6, ...,    0,    0,    0],
       [   1, 1446, 7079, ...,    0,    0,    0],
       [   1,   17,    6, ...,    0,    0,    0]])

## model Architecture

In [19]:
model = Sequential()
model.add(SimpleRNN(32,input_shape=(500,1), return_sequences=False))
model.add(Dense(1,activation='sigmoid'))
# model.add(Dense(1,activation='sigmoid'))


In [20]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn (SimpleRNN)      (None, 32)                1088      
                                                                 
 dense (Dense)               (None, 1)                 33        
                                                                 
Total params: 1121 (4.38 KB)
Trainable params: 1121 (4.38 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [21]:
model.compile(metrics=['accuracy'], optimizer = 'adam', loss='binary_crossentropy')

In [22]:
model.fit(X_train,y_train,epochs=15,validation_data=(X_test,y_test))

Epoch 1/15
782/782 [==============================] - 31s 39ms/step - loss: 0.6948 - accuracy: 0.5040 - val_loss: 0.6937 - val_accuracy: 0.5007
Epoch 2/15
782/782 [==============================] - 30s 39ms/step - loss: 0.6936 - accuracy: 0.5071 - val_loss: 0.6953 - val_accuracy: 0.5100
Epoch 3/15
782/782 [==============================] - 30s 38ms/step - loss: 0.6943 - accuracy: 0.5025 - val_loss: 0.6932 - val_accuracy: 0.5011
Epoch 4/15
782/782 [==============================] - 26s 33ms/step - loss: 0.6944 - accuracy: 0.5014 - val_loss: 0.6957 - val_accuracy: 0.5037
Epoch 5/15
782/782 [==============================] - 26s 33ms/step - loss: 0.6947 - accuracy: 0.5048 - val_loss: 0.6968 - val_accuracy: 0.4970
Epoch 6/15
782/782 [==============================] - 26s 34ms/step - loss: 0.6946 - accuracy: 0.5011 - val_loss: 0.6956 - val_accuracy: 0.5044
Epoch 7/15
782/782 [==============================] - 26s 34ms/step - loss: 0.6947 - accuracy: 0.4995 - val_loss: 0.6933 - val_accuracy:

In [23]:
model.predict(X_test)

782/782 [==============================] - 7s 9ms/step


array([[0.52136904],
       [0.52136904],
       [0.56655586],
       ...,
       [0.5212015 ],
       [0.52120155],
       [0.52136904]], dtype=float32)

In [24]:
# model.save('path.h5')
# model.save('path.pkl') # pickle


In [25]:

# model.load('path.pkl')
# model.predict(X_train[0])

## Embedding layers using keras

In [26]:
docs = ['recurrent neural network',
		'neural network',
		'artificial neural',
  
		'connections between nodes',
		'can create a cycle',
		'allowing output',
		'some nodes to affect subsequent',
		'exhibit temporal',
		'dynamic behavior',
		'type of Neural Network',
    'affect subsequent']

In [27]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

tokenizer = Tokenizer(oov_token='<nothing>')


In [28]:
tokenizer.fit_on_texts(docs)

In [29]:
tokenizer.word_index

{'<nothing>': 1,
 'neural': 2,
 'network': 3,
 'nodes': 4,
 'affect': 5,
 'subsequent': 6,
 'recurrent': 7,
 'artificial': 8,
 'connections': 9,
 'between': 10,
 'can': 11,
 'create': 12,
 'a': 13,
 'cycle': 14,
 'allowing': 15,
 'output': 16,
 'some': 17,
 'to': 18,
 'exhibit': 19,
 'temporal': 20,
 'dynamic': 21,
 'behavior': 22,
 'type': 23,
 'of': 24}

In [30]:
tokenizer.word_counts

OrderedDict([('recurrent', 1),
             ('neural', 4),
             ('network', 3),
             ('artificial', 1),
             ('connections', 1),
             ('between', 1),
             ('nodes', 2),
             ('can', 1),
             ('create', 1),
             ('a', 1),
             ('cycle', 1),
             ('allowing', 1),
             ('output', 1),
             ('some', 1),
             ('to', 1),
             ('affect', 2),
             ('subsequent', 2),
             ('exhibit', 1),
             ('temporal', 1),
             ('dynamic', 1),
             ('behavior', 1),
             ('type', 1),
             ('of', 1)])

In [31]:
tokenizer.document_count

11

In [32]:
sequences = tokenizer.texts_to_sequences(docs)
sequences

[[7, 2, 3],
 [2, 3],
 [8, 2],
 [9, 10, 4],
 [11, 12, 13, 14],
 [15, 16],
 [17, 4, 18, 5, 6],
 [19, 20],
 [21, 22],
 [23, 24, 2, 3],
 [5, 6]]

In [33]:
from keras.utils import pad_sequences

sequences = pad_sequences(sequences, padding = 'post')
sequences

array([[ 7,  2,  3,  0,  0],
       [ 2,  3,  0,  0,  0],
       [ 8,  2,  0,  0,  0],
       [ 9, 10,  4,  0,  0],
       [11, 12, 13, 14,  0],
       [15, 16,  0,  0,  0],
       [17,  4, 18,  5,  6],
       [19, 20,  0,  0,  0],
       [21, 22,  0,  0,  0],
       [23, 24,  2,  3,  0],
       [ 5,  6,  0,  0,  0]])

# model architecture

In [34]:
from keras import Sequential
from keras.layers import Dense, SimpleRNN, Embedding, Flatten

model = Sequential()
model.add(Embedding(23, output_dim=2, input_length=500))
model.add(SimpleRNN(32, input_shape = (500,1), return_sequences= False))

model.summary()


Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 500, 2)            46        
                                                                 
 simple_rnn_1 (SimpleRNN)    (None, 32)                1120      
                                                                 
Total params: 1166 (4.55 KB)
Trainable params: 1166 (4.55 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


# embedding and RNN on IMDB dataset

In [35]:
import numpy as np

from keras.datasets import imdb
imdb.load_data()


((array([list([1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 22665, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 21631, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 19193, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 10311, 8, 4, 107, 117, 5952, 15, 256, 4, 31050, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 12118, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32]),
         list([1, 19

In [36]:
# pip install keras


In [37]:
from tensorflow.keras.layers import Embedding, SimpleRNN, Dense, Input
from tensorflow.keras.models import Sequential

In [38]:
# from keras import Sequential
# from keras.layers import Dense, SimpleRNN, Embedding, Flatten

In [39]:
(X_train, y_train), (X_test, y_test) = imdb.load_data(num_words = 10000)

In [40]:
print(len(X_train[0]))
print(len(X_train[2]))

218
141


In [41]:
print(y_train[7])
print(y_train[0])

0
1


In [42]:
X_train[0]

[1,
 14,
 22,
 16,
 43,
 530,
 973,
 1622,
 1385,
 65,
 458,
 4468,
 66,
 3941,
 4,
 173,
 36,
 256,
 5,
 25,
 100,
 43,
 838,
 112,
 50,
 670,
 2,
 9,
 35,
 480,
 284,
 5,
 150,
 4,
 172,
 112,
 167,
 2,
 336,
 385,
 39,
 4,
 172,
 4536,
 1111,
 17,
 546,
 38,
 13,
 447,
 4,
 192,
 50,
 16,
 6,
 147,
 2025,
 19,
 14,
 22,
 4,
 1920,
 4613,
 469,
 4,
 22,
 71,
 87,
 12,
 16,
 43,
 530,
 38,
 76,
 15,
 13,
 1247,
 4,
 22,
 17,
 515,
 17,
 12,
 16,
 626,
 18,
 2,
 5,
 62,
 386,
 12,
 8,
 316,
 8,
 106,
 5,
 4,
 2223,
 5244,
 16,
 480,
 66,
 3785,
 33,
 4,
 130,
 12,
 16,
 38,
 619,
 5,
 25,
 124,
 51,
 36,
 135,
 48,
 25,
 1415,
 33,
 6,
 22,
 12,
 215,
 28,
 77,
 52,
 5,
 14,
 407,
 16,
 82,
 2,
 8,
 4,
 107,
 117,
 5952,
 15,
 256,
 4,
 2,
 7,
 3766,
 5,
 723,
 36,
 71,
 43,
 530,
 476,
 26,
 400,
 317,
 46,
 7,
 4,
 2,
 1029,
 13,
 104,
 88,
 4,
 381,
 15,
 297,
 98,
 32,
 2071,
 56,
 26,
 141,
 6,
 194,
 7486,
 18,
 4,
 226,
 22,
 21,
 134,
 476,
 26,
 480,
 5,
 144,
 30,
 5535,
 18,

In [43]:
# Data processing
# step 1 : Data visualization
# step 2 : padding
from keras.utils import pad_sequences
X_train = pad_sequences(X_train,padding = 'post', maxlen=50)
X_test = pad_sequences(X_test,padding = 'post', maxlen=50)


In [44]:
X_train

array([[2071,   56,   26, ...,   19,  178,   32],
       [8255,    5,    2, ...,   16,  145,   95],
       [ 215,   28,  610, ...,    7,  129,  113],
       ...,
       [   4,   65,  496, ...,    4, 3586,    2],
       [  13,   18,   31, ...,   12,    9,   23],
       [7585,    8, 2197, ...,  204,  131,    9]])

In [45]:
print(len(X_train[0]))
print(len(X_test[0]))



50
50


In [46]:
import tensorflow as tf
tf.__version__

'2.13.0'

In [47]:
# Model Architecture

# model = Sequential()

# model.add(Input(shape=(20,)))
# # model.add(Embedding(input_dim=1000 ,   output_dim=2, trainable = True))

# # model.add(Flatten())
# model.add(SimpleRNN(units=32, input_shape=(5,2) ))
# model.add(Dense(units=1,activation="sigmoid"))
# # model.add(Dense(units=1,activation="sigmoid"))
# model.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])



# model.summary()


model = Sequential()
model.add(Embedding(input_dim = 10000, output_dim = 2, input_length = 50))
model.add(SimpleRNN(32, input_shape = (50,1), return_sequences=False))
model.add(Dense(1,activation = 'sigmoid'))

model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 50, 2)             20000     
                                                                 
 simple_rnn_2 (SimpleRNN)    (None, 32)                1120      
                                                                 
 dense_1 (Dense)             (None, 1)                 33        
                                                                 
Total params: 21153 (82.63 KB)
Trainable params: 21153 (82.63 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [48]:
# model.compile

In [49]:
model.compile(metrics = ['acc'],optimizer='adam',loss='binary_crossentropy')

In [50]:
model.fit(X_train,y_train,epochs=5,validation_data=(X_test,y_test))


Epoch 1/5
782/782 [==============================] - 5s 6ms/step - loss: 0.6484 - acc: 0.5878 - val_loss: 0.5074 - val_acc: 0.7595
Epoch 2/5
782/782 [==============================] - 4s 6ms/step - loss: 0.4247 - acc: 0.8078 - val_loss: 0.4202 - val_acc: 0.8094
Epoch 3/5
782/782 [==============================] - 4s 5ms/step - loss: 0.3360 - acc: 0.8607 - val_loss: 0.4211 - val_acc: 0.8146
Epoch 4/5
782/782 [==============================] - 4s 6ms/step - loss: 0.2878 - acc: 0.8876 - val_loss: 0.4449 - val_acc: 0.8051
Epoch 5/5
782/782 [==============================] - 5s 6ms/step - loss: 0.2436 - acc: 0.9074 - val_loss: 0.4865 - val_acc: 0.7987


In [51]:
# Prediction
X_test

array([[ 394,  354,    4, ...,   14,    6,  717],
       [   5,   45,  252, ...,  125,    4, 3077],
       [   7, 2460,    2, ...,    9,   57,  975],
       ...,
       [2515,  395, 4257, ...,   21,  846, 5518],
       [  78,  232,   15, ..., 2302,    7,  470],
       [   9,   57,   65, ...,   34, 2005, 2643]])

In [52]:
# Prediction
X_test[0]


array([ 394,  354,    4,  123,    9, 1035, 1035, 1035,   10,   10,   13,
         92,  124,   89,  488, 7944,  100,   28, 1668,   14,   31,   23,
         27, 7479,   29,  220,  468,    8,  124,   14,  286,  170,    8,
        157,   46,    5,   27,  239,   16,  179,    2,   38,   32,   25,
       7944,  451,  202,   14,    6,  717])

In [53]:
# Prediction
X_test[0][0:50]

array([ 394,  354,    4,  123,    9, 1035, 1035, 1035,   10,   10,   13,
         92,  124,   89,  488, 7944,  100,   28, 1668,   14,   31,   23,
         27, 7479,   29,  220,  468,    8,  124,   14,  286,  170,    8,
        157,   46,    5,   27,  239,   16,  179,    2,   38,   32,   25,
       7944,  451,  202,   14,    6,  717])

In [54]:
# Prediction
X_test[0][0:50].reshape(1,-1).shape

(1, 50)

In [55]:
test_data = X_test[0][0:50].reshape(1,-1)

In [56]:
test_data

array([[ 394,  354,    4,  123,    9, 1035, 1035, 1035,   10,   10,   13,
          92,  124,   89,  488, 7944,  100,   28, 1668,   14,   31,   23,
          27, 7479,   29,  220,  468,    8,  124,   14,  286,  170,    8,
         157,   46,    5,   27,  239,   16,  179,    2,   38,   32,   25,
        7944,  451,  202,   14,    6,  717]])

In [57]:
model.predict(test_data)

1/1 [==============================] - 0s 87ms/step


array([[0.29928097]], dtype=float32)

In [58]:
if model.predict(test_data) < 0.5:
    print("negative review")
else:
    print("positive review")

1/1 [==============================] - 0s 15ms/step
negative review


# Stacked RNN

In [59]:
# model architecture
model = Sequential()
model.add(Embedding(input_dim = 10000, output_dim = 2, input_length = 50))
model.add(SimpleRNN(32, input_shape = (50,1), return_sequences=True))
model.add(SimpleRNN(32, input_shape = (50,1), return_sequences=False))
model.add(Dense(1,activation = 'sigmoid'))

model.summary()


Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (None, 50, 2)             20000     
                                                                 
 simple_rnn_3 (SimpleRNN)    (None, 50, 32)            1120      
                                                                 
 simple_rnn_4 (SimpleRNN)    (None, 32)                2080      
                                                                 
 dense_2 (Dense)             (None, 1)                 33        
                                                                 
Total params: 23233 (90.75 KB)
Trainable params: 23233 (90.75 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


# embedding and RNN on IMDB dataset and Bidirectional

In [60]:
from keras.datasets import imdb
from keras import Sequential
from keras.layers import Dense, SimpleRNN, Embedding, Flatten
from keras.utils import pad_sequences
from tensorflow.keras.layers import Bidirectional

In [61]:
(X_train, y_train), (X_test, y_test) = imdb.load_data(num_words = 10000)

In [62]:
# Data processing
# Step - 1  : Visualization of the data
# Step - 2: Zero Padding
X_train = pad_sequences(X_train, padding = 'post', maxlen = 50)
X_test = pad_sequences(X_test, padding = 'post', maxlen = 50)

In [63]:
X_train


array([[2071,   56,   26, ...,   19,  178,   32],
       [8255,    5,    2, ...,   16,  145,   95],
       [ 215,   28,  610, ...,    7,  129,  113],
       ...,
       [   4,   65,  496, ...,    4, 3586,    2],
       [  13,   18,   31, ...,   12,    9,   23],
       [7585,    8, 2197, ...,  204,  131,    9]])

In [64]:
X_train.shape


(25000, 50)

In [65]:
print(len(X_train[0]))
print(len(X_train[4]))

50
50


In [67]:
# model architecture
model = Sequential()
model.add(Embedding(input_dim = 10000, output_dim = 2, input_length = 50))
model.add( Bidirectional(SimpleRNN(32, input_shape = (50,1), return_sequences=False)))
model.add(Dense(1,activation = 'sigmoid'))

model.summary()

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_4 (Embedding)     (None, 50, 2)             20000     
                                                                 
 bidirectional (Bidirection  (None, 64)                2240      
 al)                                                             
                                                                 
 dense_3 (Dense)             (None, 1)                 65        
                                                                 
Total params: 22305 (87.13 KB)
Trainable params: 22305 (87.13 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [68]:
# model compile
model.compile(metrics = ['acc'], optimizer = 'adam', loss = 'binary_crossentropy')

In [69]:
# RNN model train
# model Training
model.fit(X_train, y_train, epochs = 5, validation_data = (X_test, y_test))

Epoch 1/5
782/782 [==============================] - 10s 11ms/step - loss: 0.6839 - acc: 0.5391 - val_loss: 0.5840 - val_acc: 0.7012
Epoch 2/5
782/782 [==============================] - 9s 11ms/step - loss: 0.4594 - acc: 0.7840 - val_loss: 0.4192 - val_acc: 0.8093
Epoch 3/5
782/782 [==============================] - 8s 11ms/step - loss: 0.3425 - acc: 0.8555 - val_loss: 0.4351 - val_acc: 0.8043
Epoch 4/5
782/782 [==============================] - 9s 11ms/step - loss: 0.2923 - acc: 0.8810 - val_loss: 0.4474 - val_acc: 0.8096
Epoch 5/5
782/782 [==============================] - 9s 11ms/step - loss: 0.2537 - acc: 0.9014 - val_loss: 0.4599 - val_acc: 0.7991


In [ ]:
# Prediction
X_test[0][0:50].reshape(1,-1).shape

In [ ]:
test_data = X_test[0][0:50].reshape(1,-1)

In [ ]:
# RNN model prediction
if model.predict(test_data) < 0.5:
  print('negative review')
else:
  print('positive review')


# Stacked RNN